#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: 3072inneB@
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: pdf

#Server
SERVER_PORT: 9999
ACTIVE_PROFILE: prod


