#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: 3072inneB@
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: postgres

BREVO_KEY: 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
TEMPLATE_ID: 718

#Server
SERVER_PORT: 8888
ACTIVE_PROFILE: dev
